### ISSUE TITLE
Update to new typescript version (2.6.1)

### ISSUE THREAD

**Issue by amadare42** [charto/readts#1]
What is the project status? 
Currently, it is not compatible with newest typescript version (2.6.1 at the moment). Are you willing to update it? Or at least accept PRs?

**Comment by jjrv** [comment]
Hi,

PRs are very welcome!

I'd need this to work as well, but so far other repos have been more urgent.

**Comment by SupernaviX** [comment]
I tried my hand at making a PR, it looks like it works with docts now
